### ISSUE TITLE
it also happen when i change to my own "username" & "password" strings.

### ISSUE THREAD

**Issue by bonda007** [lanmaster53/honeybadger#1]
working

**Comment by lanmaster53** [comment]
That's because `username` and `password` are supposed to be something. The only way the `NameError` exception is thrown here is when you try to use an uninstantiated variable. The readme is just an example and I tried to make it obvious that you have to provide your own data. Cope and paste the following like exactly into the terminal and it will work. If it does not, then send me the new error.

```
honeybadger.initdb('hb', 'hb')
```
